# Generated by Django 3.2.12 on 2022-02-06 06:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField(default=0)),
                ('sold', models.IntegerField(default=0)),
                ('remaining', models.IntegerField(default=0)),
                ('unit_expense', models.IntegerField(default=0)),
                ('unit_selling_price', models.IntegerField(default=0)),
                ('profit_per_item', models.IntegerField(default=0)),
                ('total_item_profit', models.IntegerField(default=0)),
                ('total_profit', models.IntegerField(default=0)),
                ('item_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myshop.items')),
            ],
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
