# Generated by Django 3.2.12 on 2022-02-06 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0003_auto_20220206_0625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='item_name',
            field=models.CharField(max_length=200),
        ),
        migrations.DeleteModel(
            name='item',
        ),
    ]
