# Generated by Django 3.2.12 on 2022-02-06 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0006_alter_product_item_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='profit_per_item',
            new_name='total_expense',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='qty',
            new_name='total_qty',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='remaining',
            new_name='unit_cost',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sold',
        ),
        migrations.RemoveField(
            model_name='product',
            name='total_item_profit',
        ),
        migrations.RemoveField(
            model_name='product',
            name='total_profit',
        ),
        migrations.RemoveField(
            model_name='product',
            name='unit_expense',
        ),
        migrations.RemoveField(
            model_name='product',
            name='unit_selling_price',
        ),
    ]
