# Generated by Django 3.2.12 on 2022-02-06 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0007_auto_20220206_1357'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sold_qty', models.IntegerField(default=0)),
                ('total_sales', models.IntegerField(default=0)),
                ('sale_unit', models.IntegerField(default=0)),
                ('item_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myshop.item')),
            ],
        ),
    ]
