# Generated by Django 3.2.12 on 2022-02-07 15:15

from django.db import migrations, models
import datetime


class Migration(migrations.Migration):

    dependencies = [
        ("myshop", "0009_product_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="date",
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name="sale",
            name="date",
            field=models.DateField(default=datetime.date.today),
        ),
    ]
