# Generated by Django 3.2.12 on 2022-02-08 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0010_auto_20220207_1515'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='total_sales',
        ),
        migrations.AlterField(
            model_name='product',
            name='date',
            field=models.DateField(default=0),
        ),
        migrations.AlterField(
            model_name='sale',
            name='date',
            field=models.DateField(default=0),
        ),
    ]
